version: '3.8'

include: 
  - proxy.yaml

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=mysql
      - DB_NAME=virtd
      - DB_USER=app
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql:rw

volumes:
  db_data: {}